### ISSUE TITLE
R2DBC improvement

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects/spring-data-r2dbc#101]
hi

with r2dbc there only insert() method to add new entity, so why not add new method insertOrUpdate (or just save) to insert entity if not exists or update it if already exists

**Comment by mp911de** [comment]
`DatabaseClient` is not an entity-based API. It is primarily SQL-oriented with a possibility to benefit from Spring Data's mapping metadata.

We currently miss update and delete methods because there is no API to express predicates. With #64 we will get these and `DatabaseClient` receives `update()` and `delete()` methods.

If you want insert or update semantics, use R2DBC repositories. `SimpleR2dbcRepository` gives you exactly that behavior considering Spring Data-specific extensions such as `Persistable`.
