### ISSUE TITLE
Delete by query doesn't seems to work as expected

### ISSUE THREAD

**Issue by cambierr** [spring-projects/spring-data-r2dbc#159]
Here is a sample repository:

```java
@Repository
public interface UserRoleRepository extends ReactiveCrudRepository<UserRole, UUID> {
    @Query("delete from account.User_Role where user_id = $1")
    Mono<Void> deleteAllByUserId(UUID userId);
}
```

This produces the error `org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class java.lang.Void!` and I'm not sure to know how to make this work and wasn't able to find anything relevant in the documentation & issues.

Any help on this ? Thank you guys !

**Comment by mp911de** [comment]
That’s a bug. Thanks for report.

**Comment by mp911de** [comment]
I investigated the issue and found that Spring Framework does not consider `Void.class` (as in `Mono<Void>`) a primitive. When Spring Framework is able to fix the issue with spring-projects/spring-framework#23572, we're basically left with just adding a test. 

The fix would be trivial on our side, otherwise.

**Comment by mp911de** [comment]
Fixed via Spring Framework.
