### ISSUE TITLE
Custom comparators for R2dbcRepository in Spring Data

### ISSUE THREAD

**Issue by LaoTsing** [spring-projects/spring-data-r2dbc#263]
**Feature Request**
Needed custom comparators for supporting special iLike, Jsonb, Arrays, Ranges and Full Text Search of PostgreSQL inline querying in Criteria builder (do not custom, only inline)

**Describe the solution you'd like**
As solution may be create comparators as bean and dynamic extending collection:

enum Comparator { EQ, NEQ, LT, LTE, GT, GTE, IS_NULL, IS_NOT_NULL, LIKE, NOT_IN, IN, }

**Comment by carhartl** [comment]
I was also facing the issue that I wanted to use a jsonb operator, such as `data ? foo`, which doesn't seem to be possible using`Criteria` at the moment. I had to resort to go lower level...

**Comment by carhartl** [comment]
E.g. I would see some value in enhancing the Criteria builder... I noticed there's `Conditions.just()`, so could there be something like a `Criteria.just()`?

**Comment by mp911de** [comment]
This ticket isn't an exact duplicate of #289 but the referenced ticket contains a few details on why this enhancement isn't really going to work. We recommend using the `execute()` API for more flexibility.

**Comment by carhartl** [comment]
Hi @mp911de, understood, I had to resort to the `execute()` api :)

Though if you don't know upfront which conditions there are going to be (think: taking filters from http request params) I found it difficult because having to `bind()` values individually. For this `Criteria` was really convenient... could there be an alternative `bind()` taking a map, or an array? Or am I overlooking something?

**Comment by mp911de** [comment]
`DatabaseClient`'s API is comparable to what `JdbcTemplate` provides though it has a tiny POJO-mapping-based API. I suggest using something like jOOQ to generate dynamic SQL statements. We do not plan to evolve the Criteria API too much. There are all sorts of ways to express the `WHERE` clause or the functionality around Postgres' Fulltext-search or any JSON query predicates so that we would end up with a massive pile of functionality and a very broad API to cater for the individual things one might want to achieve with `Criteria`.

**Comment by LaoTsing** [comment]
Criteria API it is a high level and provides a certain level of security, if we move to a lower level as jOOQ, then we will have to write a bunch of code to fully repeat the Criteria API functionality with only possibility of custom comparators )))

**Comment by mp911de** [comment]
In #265, we provide two rather simple examples. Without introducing another abstraction level we cannot infer type and parameter binding information that would be required to render proper criteria. Spring Data's support for relational databases is primary a library to implement the repository pattern and to aid common use-cases. It's by no means an exhaustive library that supports all types of features that are provided by the underlying databases.

**Comment by LaoTsing** [comment]
@mp911de 
`criterial.and("score").has("<@ int4range(1,7)")`

`has` function is planed?

**Comment by LaoTsing** [comment]
Hi @carhartl, you wrote:
> Hi @mp911de, understood, I had to resort to the `execute()` api :)

Can you show of use `execute()` api for jsonb?

**Comment by LaoTsing** [comment]
> In #265, we provide two rather simple examples. Without introducing another abstraction level we cannot infer type and parameter binding information that would be required to render proper criteria. Spring Data's support for relational databases is primary a library to implement the repository pattern and to aid common use-cases. It's by no means an exhaustive library that supports all types of features that are provided by the underlying databases.

yes, but Hibernate support custom operators

**Comment by carhartl** [comment]
@LaoTsing 

> Can you show of use execute() api for jsonb?

To give you an idea:

```java
databaseClient.execute("SELECT data FROM things WHERE data ? $1").bind(0, "foo");
```

**Comment by LaoTsing** [comment]
Thank you, but i think to as clean is supporting custom operators in Criteria API, because each database have a lot inline operators
