### ISSUE TITLE
concatenated or merged update operations ends stream?

### ISSUE THREAD

**Issue by peterfigure** [spring-projects/spring-data-r2dbc#399]
eg. I have the following:

```
        kafkaReceiver
            .subscribeOn(Schedulers.boundedElastic())
            .filter { Kafka.filterEmptyRecords(it) }
            .flatMap { rr: ReceiverRecord<String, Insurance> ->
                val reportEntryId = UUID.fromString(rr.key())
                reportEntryRepository.findById(reportEntryId).map { rr to it }
                    .log("FIRST")
            }
            .flatMap { pair: Pair<ReceiverRecord<String, Insurance>, ReportEntry> ->
                reportEntryRepository
                    .updateStateToPaid(pair.second.reportEntryId, pair.second.paidAmount)
                    .doOnSuccess { pair.first.receiverOffset().commit() }
                    .log("INNER")
            }
            .log("OUTER")
            .subscribe(
                { logger.info("materialized value $it") },
                { error -> logger.error("terminating with an error", error) }
            )
```

As it stands I will never see the OUTER log statements (I expect `doOnNext` and `onComplete` logs), nor would the consumer function in the subscribe be invoked. I do the INNER publisher completing for each record from kafka. 

When I comment out the last `flatMap` the logging and subscribe consumer works as expected.

**Comment by mp911de** [comment]
What you see is a consequence of a stream-based result consumption. As R2DBC drivers decode the result stream, they emit individual rows one by one. While they continue reading the response from your `findById` query, your stream issues update statements. The subsequent `flatMap` also awaits completion before it asks for more upstream elements. Since the connection is busy with reading the `findById` query, it cannot progress anymore as it is awaiting a response from a database query that isn't being processed yet.

I think you should be able to resolve the issue by consuming the entire response stream (e.g. `reportEntryRepository.findById(reportEntryId)…collectList().flatMapIterable(Function.identity())`).

R2DBC drivers work this way as they propagate backpressure to the TCP level. Otherwise, the entire response would be consumed which could exhaust application memory.

**Comment by peterfigure** [comment]
Thanks @mp911de - admittedly I don't fully understand your explanation, the way it reads to me it should result in a deadlock, which is not the case, the stream processes all (ie `updateStateToPaid`) the elements produced by kafka and the `findById` query, it just doesn't progress to the next step in the pipeline. 
Why do the two r2dbc operations share the same connection? Wouldn't applying backpressure on the stream element basis still effectively apply backpressure at the TCP level? (I don't know how the postgres protocol works, probably missing something here). 

I think the above scenario is not an unlikely one and this seems like MAJOR gotcha to me, I didn't find any mention in the documentation of this behaviour, did I just miss it?

**Comment by peterfigure** [comment]
Oh also, I forgot to mention, the `doOnComplete` handler (if installed) does run even though the `subscribe` consumer does not.

**Comment by peterfigure** [comment]
The proposed workaround (which won't be applicable to large or indeterminate result sets) unfortunately does not change the behaviour, the consumer function is not executed :(
