### ISSUE TITLE
Add support of DataSource configuration

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-data-r2dbc#40]
Currently Spring data Jdbc/JPA can recognize `spring.datasource` and build a `DataSource` bean, if possible create a `ConnectionFactory` bean from `spring.datasource` automatically if it is configured in Spring Boot applications?

**Comment by mp911de** [comment]
We should avoid depending on JDBC in the first place. JDBC is in any case a non-core module in the JDK originating in Java Enterprise. So it could suffer from what happened to non-core modules in the past few Java 9+ releases.

There’s a need to provide a convenient configuration mechanism (such as URI-based configuration). This might happen in R2DBC SPI itself so we gain a consistent config mechanism for drivers and client implementors.

Final note: Spring Data R2DBC currently depends on JDBC because we’re reusing Spring Frameworks Exception Translation. This is subject to be fixed as soon as Spring Framework refractors it’s mechanism.
Am 21. Dez. 2018, 14:27 +0100 schrieb Greg Turnquist <notifications@github.com>:

**Comment by odrotbohm** [comment]
For reference, I've created (SPR-17618)[https://jira.spring.io/browse/SPR-17618] to ask for the extraction of the error code translation mechanism.

**Comment by mp911de** [comment]
Spring Data R2DBC provides `AbstractR2dbcConfiguration` as configuration support. `spring.datasource` properties belong into Spring Boot and we should see support for `spring.r2dbc` properties in the future. In any case, auto-configuration components will be part of an external project so I'm closing this ticket as invalid for now.
