### ISSUE TITLE
Implicit row to class mapper does not use internal type codecs of the DB driver

### ISSUE THREAD

**Issue by gitlukasz** [spring-projects/spring-data-r2dbc#419]
MappingR2dbcConverter.readFrom reads data from Row without passing expected type. Because of it, when I try to map column of type datetime to class property of type Instant then InstantCodec from r2dbc-mysql is not used for reading. Instead of it Spring gets LocalDateTime, which later is converted to Instant using InstantToLocalDateTimeConverter. It causes a problem because IntantCodec from r2dbc-mysql supports time zone ID passed in configuration, but InstantToLocalDateTimeConverter converts to system time zone automatically. In my case I would like to store and read datetime in UTC, but with current implementation read always uses system time zone.

**Comment by mp911de** [comment]
Our `RowMapper` isn't requesting a target type because we're not distinguishing on the target type. A property might use a type that isn't supported by the driver (e.g. enum or a user-defined type for which your application registers a `Converter`). In that case, we would request a target type, an exception would be thrown and that would leave us with a performance penalty.

As per R2DBC spec, `Instant` isn't supported. `Instant` can be returned by database drivers that wish do to so. 

You could hook into the execution phase with an `ExecuteFunction` where you wrap `Row` to redirect calls for the temporal column type:

```java
return DatabaseClient.builder().connectionFactory(connectionFactory)
		.executeFunction(statement -> {

			return Flux.from(statement.execute()).map(result -> {

				return new Result() {
					@Override
					public Publisher<Integer> getRowsUpdated() {
						return result.getRowsUpdated();
					}

					@Override
					public <T> Publisher<T> map(BiFunction<Row, RowMetadata, ? extends T> mappingFunction) {
						return result
								.map((row, rowMetadata) -> mappingFunction
										.apply(new MyRow(row, rowMetadata), rowMetadata));
					}
				};	
			});
		}).build();
```


Happy to discuss other options.
