### ISSUE TITLE
Split data table horizontally

### ISSUE THREAD

**Issue by niyaode** [spring-projects/spring-data-r2dbc#427]
R2DBC is very fast.But for the database, the data Pang makes the query of the database slow. To solve this problem, we usually split the data vertically and horizontally
**split horizon**
The table structure is the same. Divide the data in a table into n tables for storage.

R2DBC Support or not

**Comment by mp911de** [comment]
Spring Data R2DBC does not need to do anything special if you need to use partitioning because the database can take care of that. From our perspective, you just read from your table, and [MySQL](https://dev.mysql.com/doc/refman/5.7/en/partitioning.html) or [PostgreSQL](https://www.postgresql.org/docs/10/static/ddl-partitioning.html) take care of routing rows internally to different partitions.

We don't plan to add further enhancements regarding sharding so closing the ticket.

**Comment by niyaode** [comment]
You may have misunderstood it.
Can  R2DBC provide functions like sharding sphere.
These functions belong to the software level.
@mp911de

**Comment by mp911de** [comment]
Thanks for clarifying. The R2DBC spec itself is agnostic towards the underlying database. All it defines is a textual interface to retrieve `Result` and `Row` objects. One could build a sharding router by using R2DBC the same way as it is used for JDBC. In any case, that topic isn't affiliated with Spring Data at all, so probably existing communities such as Apache are a better place to discuss such improvements.
