### ISSUE TITLE
Statement.execute() in ConnectionAccessor.inConnection does not execute the query

### ISSUE THREAD

**Issue by deblockt** [spring-projects/spring-data-r2dbc#428]
Hello, 

I'm trying to increase the spring-data-r2dbc from `1.0.0.RELEASE` to `spring-boot-starter-data-r2dbc:2.3.2.RELEASE`.

I have an issue using the `ConnectionAccessor.inConnection` function. 

My previous code is the following: 
```  java
   @Override
    public Mono<Void> insert(List<MyObject> objects) {
        final var upsert =
            "insert into my_table(id) " +
                "values ($1) ";

        final var saveLines = this.connectionAccessor.inConnection(it -> {
            final var statement = it.createStatement(upsert);
            objects.forEach(line -> {
                statement
                    .bind(0, line.getId())
                    .add();
            });
            return Mono.from(statement.execute());
        });

        return saveLines.then();
    }
```

With the last version, the query is not executed. 
I need to update the code like that to work fine: 
``` java
@Override
    public Mono<Void> insert(List<MyObject> objects) {
        final var upsert =
            "insert into my_table(id) " +
                "values ($1) ";

        final var saveLines = this.connectionAccessor.inConnectionMany(it -> {
            final var statement = it.createStatement(upsert);
            objects.forEach(line -> {
                statement
                    .bind(0, line.getId())
                    .add();
            });
            return Flux.from(statement.execute());
        });

        return saveLines
           .flatMap(result -> Mono.from(result.getRowsUpdated()))
          .then();
    }
```

The `.flatMap(result -> Mono.from(result.getRowsUpdated()))` is important otherwise the query is not executed, but in my case, I don't care about the query result. 

Is that a normal behaviour, or a regression?

Thanks.

**Comment by mp911de** [comment]
I'm not sure this is a Spring Data issue at all. R2DBC mandates that the result gets consumed since it's a stream-oriented way of communicating with the database. Any results that are not consumed (observed) never happened.

Please also note that you should consume results inside the `inConnection(…)` closure, otherwise you might keep a reference to an object whose connection is closed or was returned back to the pool.

From the code and description, I assume you're using the Postgres driver. Recently the driver changed its implementation. `Publisher<Result>` gives you a promise that you get a result without having the result actually produced yet.

**Comment by deblockt** [comment]
Thanks for the response, I understand the behaviour and yes I use the postgres driver.
I will move my code inside the `inConnection` thanks for the advice.

On the other hand, for insertions, this behaviour is not very intuitive.

**Comment by mp911de** [comment]
I think that non-intuitive behavior originates from the fact that no one is really interested in the updated rows count unless you're a framework. 

Please note that R2DBC SPI is designed to be consumed by framework code. Usage in application code requires additional code to ensure proper use.
