### ISSUE TITLE
Connections idle in ClientRead for queries done via DatabaseClient (execute, select, insert, update)

### ISSUE THREAD

**Issue by pmaedel** [spring-projects/spring-data-r2dbc#443]
All statements I ran with databaseClient and subsequent bind() calls are performing really bad due to them idling for quite some time with wait_event ClientRead.

Please see attached the difference with running the same statements via r2dbc compared to vertx-sql-client:
<img width="1428" alt="r2dbc_vs_pgclient" src="https://user-images.githubusercontent.com/423462/92301986-9265be00-ef68-11ea-8367-497c4ce42ba4.png">

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by pmaedel** [comment]
I would like to provide a sample that reproduces the problem but do not know how I can reveal the state of sessions at runtime without AWS tooling as shown above. Do you have any pointers there for me?

**Comment by mp911de** [comment]
Looking at the definition of `ClientRead`, that means that the database waits for the client to read its data. R2DBC drivers are backpressure-aware so data gets consumed potentially at a later time. This issue is in any case a R2DBC Postgres driver issue and not a Spring Data one. You can find the issue tracker for the driver at https://github.com/pgjdbc/r2dbc-postgresql.

It would make sense to provide a reproducer that shows the problem when filing a ticket there.

Closing this ticket here as there's nothing we can do on the Spring side.

**Comment by pmaedel** [comment]
the issue has resolved itself after update to Spring Boot 2.4.x
