### ISSUE TITLE
R2DBC client logging $1 instead of real values on parametrized queries

### ISSUE THREAD

**Issue by Slava96** [spring-projects/spring-data-r2dbc#456]
We use spring-boot-starter-data-r2dbc version 2.3.1-RELEASE.

When we use such code as this:
`query(where("instance_id").is(instanceId))`
on log we see this:
`[SELECT parts.* FROM parts WHERE parts.instance_id = $1]`

How can we see real value of `instanceId` on log instead of $1?

**Comment by mp911de** [comment]
`SELECT parts.* FROM parts WHERE parts.instance_id = $1` is the actual string that is being sent to the database/database driver. You can enable parameter logging using https://github.com/r2dbc/r2dbc-proxy. Since R2DBC core support was migrated to Spring Framework, any follow-up should happen in a ticket in https://github.com/spring-projects/spring-framework.
