### ISSUE TITLE
Ask questions

### ISSUE THREAD

**Issue by ChenZheOnePiece** [spring-projects/spring-data-r2dbc#464]
I have some questions to ask

1.  If I want to join multiple tables, can I use jpql only, and does DatabaseClient support it
2.  Will r2dbc support jpaspecification executor in the future
3.  How long do you think r2dbc will take, like JPA

**Comment by mp911de** [comment]
R2DBC isn't JDBC and therefore it's not compatible with JPA. 

> 1. If I want to join multiple tables, can I use jpql only, and does DatabaseClient support it

You can provide your own SQL query that contains `JOIN` clauses.

> 2. Will r2dbc support jpaspecification executor in the future

It does not and it won't ever support JPA Specifications

> 3. How long do you think r2dbc will take, like JPA

JPA follows a different concept than Spring Data R2DBC/JDBC do. I think Spring Data R2DBC won't ever reach the same level of features that JPA provides because they are conceptually entirely different.
