### ISSUE TITLE
Provide a bindNullable function

### ISSUE THREAD

**Issue by deblockt** [spring-projects/spring-data-r2dbc#482]
I have an issue with the fluent way to bind variable on a `GenericExecuteSpec`.
It's very cool to have a fluent and imutable way to build the SQL request, but null values broke the fluent style.

an exemple:
``` java
 public Mono<Void> insert(String nullable, String value){
            final var query = this.databaseClient.execute("INSERT INTO test VALUES(:nonNull, :nullable)")
                .bind("nonNull", value);
            final DatabaseClient.GenericExecuteSpec queryWithNullable;
            if (nullable != null) {
                queryWithNullable = query.bind("nullable", nullable);
            } else {
                queryWithNullable = query.bindNull("nullable", String.class);
            }
            return queryWithNullable.then();
        }
```

Since `GenericExecuteSpec` is immutable with should create a new variable for each nullable.  I tried to use an optional, but it didn't work. 
   
Have a `bindNullable` or a optional support could be nice.
``` java
 public Mono<Void> insert(String nullable, String value){
            return this.databaseClient.execute("INSERT INTO test VALUES(:nonNull, :nullable)")
                .bind("nonNull", value)
                .bindNullable("nullable", nullable, String.class);
                 .then();
        }
```

Did I miss something to make it simpler?

**Comment by mp911de** [comment]
For version 1.1, you can bind potentially null values by wrapping these in `SettableValue.fromOrEmpty(...)` and then call just `bind(...)`. Since version 1.2 (`DatabaseClient` went into `spring-r2dbc`), we introduced a replacement named `org.springframework.r2dbc.core.Parameter`.

Most databases require a typed null value and we didn't want to pollute the API. 

Going forward, the wrapper approach will make its way into the R2DBC spec with a slight extension. The actual database type is now derived from the value/Java class. The wrapper will be extended to take a type parameter (e.g. `Types.VARCHAR`, `Types.NVARCHAR`).
Once that's in place, we will accept the R2DBC wrapper in `DatabaseClient`.
