### ISSUE TITLE
IN-clause empty collection

### ISSUE THREAD

**Issue by mkluzacek** [spring-projects/spring-data-r2dbc#508]
Hi,
I am using spring data r2dbc version 1.1.5 and i have the same problem as mentioned here https://jira.spring.io/browse/DATAJPA-606.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mkluzacek** [comment]
I created simple(hopefully) project recreating the issue https://github.com/mkluzacek/spring-r2dbc-in-clause-problem. It doesnt work with spring boot parent 2.3.5 and data r2dbc 1.1.5. But work with spring boot parent 2.4.0 that uses data r2dbc 1.2.1. So it was fixed somewhere along the way.
We might just use the new spring boot once it has a release version.

**Comment by mkluzacek** [comment]
Sorry need to create the repo again. Need a sec.

**Comment by mp911de** [comment]
Thanks a lot. Empty `IN` handling requires API changes in Spring Data Relational, that's why we didn't backport it to earlier versions. See DATAJDBC-604 and #466. I filed DATAJDBC-639 to ask for a backport to Spring Data Relational 2.0.x which is used by Spring Data R2DBC 1.1.x.

In any case, that's an external change.

**Comment by mkluzacek** [comment]
Thanks for the quick response.
