### ISSUE TITLE
Do you plan to implement a ReactivePagingAndSortingRepository?

### ISSUE THREAD

**Issue by julien-piccaluga** [spring-projects/spring-data-r2dbc#535]
Hello,

We need both Paging and Sorting fonctionalities.

Today only Sorting through `ReactiveSortingRepository` is avaiable. 
Is there a plan to also support Pagination at Repository level as well? For example have a ReactivePagingAndSortingRepository interface which provides `findAll(Pageable pageable): Mono<Page<T>> ` method?

This will avoid to implement something like this at service layer:

```
fun fetchAll(pageable: Pageable) : Mono<Page<User>> {
        return Mono
            .zip(
                userRepository.count(), 
                userRepository.findAll(pageable.sort)
                    .skip(pageable.offset)
                    .take(pageable.pageSize.toLong())
                    .map { toModel(it) }
                    .collectList())
            .map { 
                PageImpl(it.t2, pageable, it.t1)
            }
    }
```

Regards

Julien

**Comment by mp911de** [comment]
Right now, we don't. There are a couple reasons:

1. You can build this functionality yourself by combining query and count methods
2. Pagination requires collecting (consuming) the resulting objects before a method can return a `Page` object. That is, because `Page` encapsulates a collection which isn't reactive
3. Collecting elements into a `Page` removes the streaming nature and that isn't the right way while we guarantee at every other level end to end reactive streaming capabilities. We'd constrain ourselves to an API that we do not like.
