### ISSUE TITLE
Stored Procedure Bind Values(null or not null) 

### ISSUE THREAD

**Issue by upen4a3** [spring-projects/spring-data-r2dbc#537]
Hi Currently I am using databaseclient to execute stored procedure against mysql.My SP have 5+ in parameters which can be null sometimes.The Problem I was facing is if use bind it requires value like 

`databaseClient.execute(STORED_PROC).bind("someParam",someValue)`

If I pass null value in bind i will get an exception saying bind value cannot be null.

and In the above someValue can be null sometimes.

so currently i have to use if else statement to bind both null and non null value like below

 ```
        var result: DatabaseClient.GenericExecuteSpec = databaseClient.execute(STORED_PROC)
        if (someValue != null) 
            result.bind("someParam", someValue) 
        else {
            result.bindNull("planVar", String::class.java)
        }
        val response:Mono<String> = result.`as`(String::class.java).fetch().one()
```

Is there a way I can bind a value which is optional?

**Comment by mp911de** [comment]
Basically what you're asking is a way to avoid `if` for the sake of calling `bind` vs. `bindNull`. Since parameter bindings must be typed (also for `null`), you will have to specify a type in any case. You can use the `Parameter` with `DatabaseClient`:

```kotlin
databseClient.execute(…).bind("someParam", Parameter.fromOrEmpty(value, String::class.java)
```

Note that `Parameter` stems from Spring Framework. Looking at the code, it would be nice to write `Parameter.<String>.fromOrEmpty` instead of passing on the Java class. Feel free to file a ticket in https://github.com/spring-projects/spring-framework/issues for a Kotlin extension.
