### ISSUE TITLE
Deprecate `*ConverterOverride` classes in favor of `R2dbcCustomConversionsConfiguration` converter filters

### ISSUE THREAD

**Issue by magiccrafter** [spring-projects/spring-data-r2dbc#750]
Hi team,

I'm struggling to understand the reasoning for having the converter overrides from the code snippet below:

from: `R2dbcConverters`
```java
	/**
	 * @return A list of the registered converters to enforce JSR-310 type usage.
	 * @see CustomConversions#DEFAULT_CONVERTERS
	 * @see Jsr310Converters
	 */
	public static Collection<Object> getOverrideConvertersToRegister() {

		List<Object> converters = new ArrayList<>();

		converters.add(LocalDateConverterOverride.INSTANCE);
		converters.add(LocalDateTimeConverterOverride.INSTANCE);
		converters.add(LocalTimeConverterOverride.INSTANCE);

		return converters;
	}
```

The problem I face is that because of the overrides from the snippet above any custom converters specified for a custom `R2dbcDialect` implementation is being overridden and respectively ignored. 

For example, in the following custom R2dbcDialect class the converters are ignored and the `*Override`'s one take precedence:
``` java
public class CustomR2dbcDialect extends AbstractDialect implements R2dbcDialect {
   ...
    @Override
    public Collection<? extends Class<?>> getSimpleTypes() {
      return Arrays.asList(
        XTimestamp.class,
        XDate.class);
    }
  
    @Override
    public Collection<Object> getConverters() {
      return Arrays.asList(
        new LocalDateToXDateConverter(),
        new XDateToLocalDateConverter(),
        new LocalDateTimeToXTimestampConverter(),
        new XTimestampToLocalDateTimeConverter());
    }
    ...
  }
  ```

What is the purpose of the *ConverterOverride classes and does it make sense to remove the converter overrides?

**Comment by magiccrafter** [comment]
To workaround the above problem one could possibly define a `R2dbcCustomConversions` bean with the converters that are being overrriden:
```java
@Bean
@ConditionalOnMissingBean
public R2dbcCustomConversions customConversions() {
    return R2dbcCustomConversions.of(
        new XR2dbcDialect(),
        Arrays.asList(
            new LocalDateToXDateConverter(),
            new XDateToLocalDateConverter(),
            new LocalDateTimeToXTimestampConverter(),
            new XTimestampToLocalDateTimeConverter()
        )
    );
}
```
This wrapped in an Autoconfigure class provided by the client library seems like a proper hack 🤔 
It would be great if there is a more elegant way to avoid the custom *Override.java clases.

**Comment by mp911de** [comment]
`…ConverterOverride` classes are in place to apply identity conversion. Spring Data Commons auto-registers by default converters that convert [JSR-310 temporal types to `java.util.Date`](https://github.com/spring-projects/spring-data-commons/blob/d10822e6bd7a07ce115a5dc3a349ad7f6a64f365/src/main/java/org/springframework/data/convert/Jsr310Converters.java#L126) which isn't desired in a R2DBC arrangement. However, with JDBC, MongoDB, and Cassandra `LocalDate` to `java.util.Date` makes sense.

The R2DBC [converter configuration deliberately filters converters](https://github.com/spring-projects/spring-data-r2dbc/blob/a46b6751a52042a33a05c59ee6590f69e2b3c869/src/main/java/org/springframework/data/r2dbc/convert/R2dbcCustomConversions.java#L104-L106) that want to convert from JSR-310 temporal types into `java.util.Date`.

Creating custom conversions via `R2dbcCustomConversions.of(…)` is the proper way to customize converters as the custom conversions object applies typically per Spring Data module and you want to properly isolate converters.

I think the underlying issue should be solved in order to make your conversion work. That is, that the underlying driver doesn't support JSR-310 temporal types. While at it, we should be able to remove our `…ConverterOverride` types as we have the aforementioned converter filter in place anyway.
