### ISSUE TITLE
[AbstractR2dbcConfiguration] Found an interesting post on stackoverflow related to AbstractR2dbcConfiguration

### ISSUE THREAD

**Issue by zhouxos** [spring-projects/spring-data-r2dbc#804]
https://stackoverflow.com/questions/66887036/why-does-the-annotation-transactional-not-work-in-the-case-of-custom-abstractr2
In his example, looks like transactional manager works with `r2dbcEntityTemplate` but not with `CrudRepository`
can i get some insights on why this is the case?

**Comment by mp911de** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [StackOverflow](https://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-data-build/blob/main/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by zhouxos** [comment]
thanks! i have resolved the issue and answer the questions.
